### ISSUE TITLE
Upload to hackage

### ISSUE THREAD

**Issue by wraithm** [lpsmith/linux-inotify#6]
@lpsmith We've got a pull request to upgrade to GHC 8 in a backwards incompatible way. Would you mind merging that and uploading to hackage? Thanks!

**Comment by turboMaCk** [comment]
I would like to :+1: this.

I'm also thinking about using this library but I'm not sure if it's still maintained given https://github.com/lpsmith/linux-inotify/commit/b441753a199e0034a42b1f6b9fc8499c673063cb was merged quite some time ago but new version was still not published.

**Comment by wraithm** [comment]
I think I'm actually a maintainer now, lol. I could upload it.

**Comment by wraithm** [comment]
Oh wait, I did upload new stuff! I'm pretty sure [0.3.0.2](http://hackage.haskell.org/package/linux-inotify-0.3.0.2) has everything.

**Comment by wraithm** [comment]
@turboMaCk If there's something more you're looking for, then I'll definitely take what you got (or implement what you need) and push it to hackage.
